home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('buscar_dados/<str:app_modelo>/',views.buscar_dados, name='buscar_dados'),
    
    ############################## PRODUTO ####################################
    path('produto/', views.produto, name='produto'),
    path('form_produto/', views.form_produto, name='form_produto'),
    path('editar_produto/<int:id>/', views.editar_produto, name='editar_produto'),
    path('remover_produto/<int:id>/', views.remover_produto, name='remover_produto'),
    path('ajustar_estoque/<int:id>/', views.ajustar_estoque, name='ajustar_estoque'),
    
    ############################## CLIENTE ####################################
    path('cliente/', views.cliente, name='cliente'),
    path('form_cliente/', views.form_cliente, name='form_cliente'),
    path('editar_cliente/<int:id>/', views.editar_cliente, name='editar_cliente'),
    path('remover_cliente/<int:id>/', views.remover_cliente, name='remover_cliente'),

    ############################### PEDIDO #####################################
    path('pedido/', views.pedido, name='pedido'),
    path('pedido/<int:pedido_id>/', views.detalhar_pedido, name='detalhar_pedido'),
    path('novo_pedido/<int:id_cliente>/',views.novo_pedido, name='novo_pedido'),
    path('pedido/item/<int:item_id>/editar/', views.editar_item_pedido, name='editar_item_pedido'),
    path('pedido/item/<int:item_id>/remover/', views.remover_item_pedido, name='remover_item_pedido'),
    path('remover_pedido/<int:id>/', views.remover_pedido, name='remover_pedido'),
    path('form_pagamento/<int:id>/', views.form_pagamento, name='form_pagamento'),    
    path('editar_pagamento/<int:id>/', views.editar_pagamento, name='editar_pagamento'),
    path('remover_pagamento/<int:id>/', views.remover_pagamento, name='remover_pagamento'),   
]

pweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
import locale
from django.db import models


#locale.setlocale(locale.LC_ALL, "Portuguese_Brazil.1252")

#locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

#locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')  # ou algum outro locale disponível


# Create your models here.

class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=15,verbose_name="C.P.F")
    datanasc = models.DateField(verbose_name="Data de Nascimento")


    def __str__(self):
        return self.nome
    
    @property
    def datanascimento(self):
        """Retorna a data de nascimento no formato DD/MM/AAAA"""
        if self.datanasc:
            return self.datanasc.strftime('%d/%m/%Y')
        return None

class Categoria(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Produto(models.Model):
    nome = models.CharField(max_length=100)
    preco = models.DecimalField(max_digits=10, decimal_places=2,blank=False)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    img_base64 = models.TextField(blank=True)

    def __str__(self):
        return self.nome
    
    @property
    def preco_formatado(self):
        return self.preco
    
    @property
    def estoque(self):
        # Tenta buscar o estoque, se não existir, cria um novo com qtde 0
        estoque_item, created = Estoque.objects.get_or_create(produto=self, defaults={'qtde': 0})
        return estoque_item
   
    
############################### PEDIDO ##############################################
class Pedido(models.Model):
    NOVO = 1
    EM_ANDAMENTO = 2
    CONCLUIDO = 3
    CANCELADO = 4

    STATUS_CHOICES = [
        (NOVO, 'Novo'),
        (EM_ANDAMENTO, 'Em Andamento'),
        (CONCLUIDO, 'Concluído'),
        (CANCELADO, 'Cancelado'),
    ]

    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    produtos = models.ManyToManyField(Produto, through='ItemPedido')
    data_pedido = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=NOVO)

    def __str__(self):
            return f"Pedido {self.id} - Cliente: {self.cliente.nome} - Status: {self.get_status_display()}"
    
    @property
    def data_pedidof(self):
        """Retorna a data no formato DD/MM/AAAA HH:MM"""
        if self.data_pedido:
            return self.data_pedido.strftime('%d/%m/%Y %H:%M')
        return None
    
    @property
    def total(self):
        """Calcula o total de todos os itens no pedido, formatado como moeda local"""
        total = sum(item.qtde * item.preco for item in self.itempedido_set.all())
        return total

    
    @property
    def qtdeItens(self):
        """Conta a qtde de itens no pedido, """
        return self.itempedido_set.count()   
    
    @property
    def pagamentos(self):
        return Pagamento.objects.filter(pedido=self)   
    
    @property
    def total_pago(self):
        """Calcula o total de todos os pagamentos no pedido"""
        total = sum(pagamento.valor for pagamento in self.pagamentos.all())
        return total
    
    @property
    def debito(self):
        return self.total - self.total_pago
                        
class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    qtde = models.PositiveIntegerField()
    preco = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.produto.nome} (Qtd: {self.qtde}) - Preço Unitário: {self.preco}"

    @property
    def total(self):
        return (self.preco*self.qtde)
     
    @property
    def preco_formatado(self):
        return self.preco
    
################################## ESTOQUE ######################################
    
class Estoque(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    qtde = models.IntegerField()

    def __str__(self):
        return f'{self.produto.nome} - Quantidade: {self.qtde}'
    
    
############################### PAGAMENTO ##############################################
class Pagamento(models.Model):
    DINHEIRO = 1
    CARTAO = 2
    PIX = 3
    OUTRA = 4

    FORMA_CHOICES = [
        (DINHEIRO, 'Dinheiro'),
        (CARTAO, 'Cartão'),
        (PIX, 'Pix'),
        (OUTRA, 'Outra'),
    ]

    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    forma = models.IntegerField(choices=FORMA_CHOICES)
    valor = models.DecimalField(max_digits=10, decimal_places=2,blank=False)
    data_pgto = models.DateTimeField(auto_now_add=True)
    
    @property
    def data_pgtof(self):
        """Retorna a data no formato DD/MM/AAAA HH:MM"""
        if self.data_pgto:
            return self.data_pgto.strftime('%d/%m/%Y %H:%M')
        return None

home/forms.py
from django import forms
from .models import *
import datetime
from django.core.exceptions import ValidationError
from decimal import Decimal, InvalidOperation


class ProdutoForm(forms.ModelForm):
    #preco = forms.CharField()  # Substitui o FloatField ou DecimalField por um CharField
    class Meta:
        model = Produto
        fields = ['nome', 'preco', 'categoria','img_base64']
       

        widgets = {
            # categoria fica oculta pq foi implementado autocomplete com jquery
            # em javascript/Funcoes.js
            # em form.html de produto o input categoria e colocado no codigo diretamente
            'categoria': forms.HiddenInput(),  # Campo oculto para armazenar o ID
            'nome':forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome'}),
            'img_base64': forms.HiddenInput(), 
            # a classe money mascara a entreda de valores monetários, está em base.html
            #  jQuery Mask Plugin
            'preco':forms.TextInput(attrs={
                'class': 'money form-control',
                'maxlength': 500,
                'placeholder': '0.000,00'
            }),
        }
        
        labels = {
            'nome': 'Nome do Produto',
            'preco': 'Preço do Produto',
        }
        
    def __init__(self, *args, **kwargs):
        super(ProdutoForm, self).__init__(*args, **kwargs)
        self.fields['preco'].localize = True
        self.fields['preco'].widget.is_localized = True    



class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'cpf', 'datanasc']
        widgets = {
            'nome':forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome'}),
            'cpf':forms.TextInput(attrs={'class': 'cpf form-control', 'placeholder': 'C.P.F'}),
            'datanasc': forms.DateInput(attrs={'class': 'data form-control', 'placeholder': 'Data de Nascimento'}, format='%d/%m/%Y'),
        }
        


    

class MeuFormulario(forms.Form):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Seu nome'}))
    senha = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Sua senha'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Seu e-mail'}))
    data_nascimento = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    mensagem = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4}))
    categoria = forms.ChoiceField(choices=[('1', 'Categoria 1'), ('2', 'Categoria 2'),], widget=forms.Select(attrs={'class': 'form-control'}))



class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['cliente']
        widgets = {
            'cliente': forms.HiddenInput(),  # Campo oculto para armazenar o ID
        }
        

class ItemPedidoForm(forms.ModelForm):
    class Meta:
        model = ItemPedido
        fields = ['produto', 'qtde']

        widgets = {
            'produto': forms.HiddenInput(),  # Campo oculto para armazenar o ID
            'qtde':forms.TextInput(attrs={'class': 'form-control',}),
        }
    # Ajustes de formatação
    """
    def __init__(self, *args, **kwargs):
        super(ItemPedidoForm, self).__init__(*args, **kwargs)
        self.fields['produto'].queryset = Produto.objects.all()  # Lista todos os produtos disponíveis
        self.fields['qtde'].widget.attrs.update({'class': 'form-control'})  # Adiciona classe bootstrap
        self.fields['produto'].widget.attrs.update({'class': 'form-control'})  # Adiciona classe bootstrap
    """
    
class EstoqueForm(forms.ModelForm):
    class Meta:
        model = Estoque
        fields = ['produto','qtde']
        
        widgets = {
            'produto': forms.HiddenInput(),  # Campo oculto para armazenar o ID
            'qtde':forms.TextInput(attrs={'class': 'inteiro form-control',}),
    }
        
class PagamentoForm(forms.ModelForm):
    class Meta:
        model = Pagamento
        fields = ['pedido','forma','valor']
        widgets = {
            'pedido': forms.HiddenInput(),  # Campo oculto para armazenar o ID
            'forma': forms.Select(attrs={'class': 'form-control'}),  # Usando Select para renderizar as opções
            'valor':forms.TextInput(attrs={
                'class': 'money form-control',
                'maxlength': 500,
                'placeholder': '0.000,00'
            }),
         }
        
    def __init__(self, *args, **kwargs):
            super(PagamentoForm, self).__init__(*args, **kwargs)
            self.fields['valor'].localize = True
            self.fields['valor'].widget.is_localized = True       
    
    def clean_valor(self):
        valor = self.cleaned_data.get('valor')
        if valor <= 0:
            raise forms.ValidationError("O valor deve ser maior que zero.")
        return valor

templates/produto/estoque.html
{% extends "base.html" %}

{% block titulo_conteudo %} Ajuste de Estoque {% endblock titulo_conteudo %}

{% block conteudo %} 
<p>
    <label for="id_produto">Produto:</label>
    <span class="form-control" >{{form.instance.produto.nome}}</span>
    </p>
<form method="post">
    {% csrf_token %}    
    {{ form.as_p }}
    <button class="btn btn-primary btn-sm" type="submit">Salvar</button>
</form>
{% endblock conteudo %}

{% block javascript %}{% endblock javascript %}

templates/produto/form.html
{% extends "base.html" %}

{% block titulo_conteudo %} Formulário de Produtos {% endblock titulo_conteudo %}

{% block conteudo %} 
<form method="post">
    {% csrf_token %}    
    {{ form.as_p }}
    <p>
    <label for="id_categoria_nome">Categoria:</label>
    <!-- autocomplete -->
    <input type="text" value="{{form.instance.categoria}}" class="form-control autocomplete" id="id_categoria_nome" data-url="{% url 'buscar_dados' 'home.Categoria' %}" data-hidden="#id_categoria" >
    </p>
    <fieldset class="fieldset">
        <label for="imagem">Imagem:</label>
        <input type="hidden" id="img_base64"  class="img_init" data-canvas="imageCanvas" value="{{form.instance.img_base64}}" name="img_base64">
        <input type="file" id="imagem" name="imagem" data-hidden="img_base64" class="img_upload form-control" accept="image/*"><br>
        <canvas class="canvas"  id="imageCanvas" width="200" height="200"></canvas><br>
    </fieldset>
    <p>
    
</p>

    <button class="btn btn-primary btn-sm" type="submit">Salvar</button>


    

</form>

{% endblock conteudo %}

{% block javascript %}
<script>


    $(document).ready(function() {

        // Configura inicialização das imagens base64 para todo campo da classe img_init
        $('.img_init').each(function() {
            const initialImageBase64 = $(this).val();
            const target_canvas = $(this).data('canvas');
            if (initialImageBase64) {
                loadImage(initialImageBase64,target_canvas);
            }
        });
        
        // Evento acionado quando uma nova imagem é selecionada
        $('.img_upload').on('change', function(event) {
            
            const imagemInput = this.files[0]; // Pega o arquivo selecionado
            var hidden = $(this).data('hidden');  // Pega o campo hidden associado ao file input
            if (imagemInput) {
                const reader = new FileReader();
                reader.readAsDataURL(imagemInput); // Converte a imagem para base64

                reader.onload = function() {
                    const imgBase64 = reader.result; // O resultado da conversão
                    $('#'+hidden).val(imgBase64); // Seta o valor base64 no campo hidden associado ao file input
                    var canvasTarget = $('#'+hidden).data('canvas'); // pega o canvas associado ao compo hidden
                    // Exibe a nova imagem no canvas
                    loadImage(imgBase64,canvasTarget);
                };

                reader.onerror = function(error) {
                    console.log('Erro ao converter a imagem: ', error);
                };
            }
        });
    });
</script>

{% endblock javascript %}

templates/produto/lista.html
{% extends "base.html" %}

{% block titulo_conteudo %} Listagem de Produtos {% endblock titulo_conteudo %}

{% block conteudo %} 

<div class="barrabotoes">
<button onClick="location='{% url "form_produto" %}'" type="button" class="btn btn-primary btn-sm">Inserir Novo</button>
<button onClick="location='{% url "produto" %}'" type="button" class="btn btn-primary btn-sm">Recarregar</button>

</div>

<table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Preço(R$)</th>
        <th>Categoria</th>
        <th>Estoque</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
    {% for produto in lista_produtos %}
      <tr>
        <td>{{ produto.id }}</td>
        <td>{{ produto.nome }}</td>
        <td>{{ produto.preco_formatado }}</td>
        <td>{{ produto.categoria }}</td>
        <td>{{ produto.estoque.qtde }}</td>
        <td>
          <a href="{% url 'editar_produto' produto.id %}" class="btn btn-warning btn-sm">Editar</a>
          <a href="{% url 'ajustar_estoque' produto.id %}" class="btn btn-info btn-sm">Estoque</a>
          <a href="{% url 'remover_produto' produto.id %}" class="btn btn-danger btn-sm" 
          onclick="return confirm('Tem certeza que deseja remover este registro?');">Remover</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


{% endblock conteudo %}