home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('buscar_dados/<str:app_modelo>/',views.buscar_dados, name='buscar_dados'),
    
    ############################## PRODUTO ####################################
    path('produto/', views.produto, name='produto'),
    path('form_produto/', views.form_produto, name='form_produto'),
    path('editar_produto/<int:id>/', views.editar_produto, name='editar_produto'),
    path('remover_produto/<int:id>/', views.remover_produto, name='remover_produto'),
    path('ajustar_estoque/<int:id>/', views.ajustar_estoque, name='ajustar_estoque'),
    
    ############################## CLIENTE ####################################
    path('cliente/', views.cliente, name='cliente'),
    path('form_cliente/', views.form_cliente, name='form_cliente'),
    path('editar_cliente/<int:id>/', views.editar_cliente, name='editar_cliente'),
    path('remover_cliente/<int:id>/', views.remover_cliente, name='remover_cliente'),

    ############################### PEDIDO #####################################
    path('pedido/', views.pedido, name='pedido'),
    path('pedido/<int:pedido_id>/', views.detalhar_pedido, name='detalhar_pedido'),
    path('novo_pedido/<int:id_cliente>/',views.novo_pedido, name='novo_pedido'),
    path('pedido/item/<int:item_id>/editar/', views.editar_item_pedido, name='editar_item_pedido'),
    path('pedido/item/<int:item_id>/remover/', views.remover_item_pedido, name='remover_item_pedido'),
    path('remover_pedido/<int:id>/', views.remover_pedido, name='remover_pedido'),
    path('form_pagamento/<int:id>/', views.form_pagamento, name='form_pagamento'),    
    path('editar_pagamento/<int:id>/', views.editar_pagamento, name='editar_pagamento'),
    path('remover_pagamento/<int:id>/', views.remover_pagamento, name='remover_pagamento'),   
]

pweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
import locale
from django.db import models


#locale.setlocale(locale.LC_ALL, "Portuguese_Brazil.1252")

#locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

#locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')  # ou algum outro locale disponível


# Create your models here.

class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=15,verbose_name="C.P.F")
    datanasc = models.DateField(verbose_name="Data de Nascimento")


    def __str__(self):
        return self.nome
    
    @property
    def datanascimento(self):
        """Retorna a data de nascimento no formato DD/MM/AAAA"""
        if self.datanasc:
            return self.datanasc.strftime('%d/%m/%Y')
        return None

class Categoria(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Produto(models.Model):
    nome = models.CharField(max_length=100)
    preco = models.DecimalField(max_digits=10, decimal_places=2,blank=False)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    img_base64 = models.TextField(blank=True)

    def __str__(self):
        return self.nome
    
    @property
    def preco_formatado(self):
        return self.preco
    
    @property
    def estoque(self):
        # Tenta buscar o estoque, se não existir, cria um novo com qtde 0
        estoque_item, created = Estoque.objects.get_or_create(produto=self, defaults={'qtde': 0})
        return estoque_item
   
    
############################### PEDIDO ##############################################
class Pedido(models.Model):
    NOVO = 1
    EM_ANDAMENTO = 2
    CONCLUIDO = 3
    CANCELADO = 4

    STATUS_CHOICES = [
        (NOVO, 'Novo'),
        (EM_ANDAMENTO, 'Em Andamento'),
        (CONCLUIDO, 'Concluído'),
        (CANCELADO, 'Cancelado'),
    ]

    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    produtos = models.ManyToManyField(Produto, through='ItemPedido')
    data_pedido = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=NOVO)

    def __str__(self):
            return f"Pedido {self.id} - Cliente: {self.cliente.nome} - Status: {self.get_status_display()}"
    
    @property
    def data_pedidof(self):
        """Retorna a data no formato DD/MM/AAAA HH:MM"""
        if self.data_pedido:
            return self.data_pedido.strftime('%d/%m/%Y %H:%M')
        return None
    
    @property
    def total(self):
        """Calcula o total de todos os itens no pedido, formatado como moeda local"""
        total = sum(item.qtde * item.preco for item in self.itempedido_set.all())
        return total

    
    @property
    def qtdeItens(self):
        """Conta a qtde de itens no pedido, """
        return self.itempedido_set.count()   
    
    @property
    def pagamentos(self):
        return Pagamento.objects.filter(pedido=self)   
    
    @property
    def total_pago(self):
        """Calcula o total de todos os pagamentos no pedido"""
        total = sum(pagamento.valor for pagamento in self.pagamentos.all())
        return total
    
    @property
    def debito(self):
        return self.total - self.total_pago
                        
class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    qtde = models.PositiveIntegerField()
    preco = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.produto.nome} (Qtd: {self.qtde}) - Preço Unitário: {self.preco}"

    @property
    def total(self):
        return (self.preco*self.qtde)
     
    @property
    def preco_formatado(self):
        return self.preco
    
################################## ESTOQUE ######################################
    
class Estoque(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    qtde = models.IntegerField()

    def __str__(self):
        return f'{self.produto.nome} - Quantidade: {self.qtde}'
    
    
############################### PAGAMENTO ##############################################
class Pagamento(models.Model):
    DINHEIRO = 1
    CARTAO = 2
    PIX = 3
    OUTRA = 4

    FORMA_CHOICES = [
        (DINHEIRO, 'Dinheiro'),
        (CARTAO, 'Cartão'),
        (PIX, 'Pix'),
        (OUTRA, 'Outra'),
    ]

    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    forma = models.IntegerField(choices=FORMA_CHOICES)
    valor = models.DecimalField(max_digits=10, decimal_places=2,blank=False)
    data_pgto = models.DateTimeField(auto_now_add=True)
    
    @property
    def data_pgtof(self):
        """Retorna a data no formato DD/MM/AAAA HH:MM"""
        if self.data_pgto:
            return self.data_pgto.strftime('%d/%m/%Y %H:%M')
        return None

templates/pedido/detalhes.html
{% extends "base.html" %}

{% block titulo_conteudo %} Detalhes do Pedido #{{ pedido.id }} {% endblock titulo_conteudo %}

{% block conteudo %} 

<!-- templates/pedido/detalhar_pedido.html -->
<p><strong>Cliente:</strong> {{ pedido.cliente.nome }}</p>
<p><strong>Data do Pedido:</strong> {{ pedido.data_pedido|date:"d/m/Y H:i" }}</p>
<p><strong>Status:</strong> {{ pedido.get_status_display }}</p>

<hr>
<!-- Formulário para adicionar novos produtos -->
<h5>Adicionar Produto</h5>
<form method="POST">
    {% csrf_token %}
    <p>
     <label for="id_produto_nome">Produto:</label>    
    <input type="text" class="form-control autocomplete" id="id_produto_nome" data-url="{% url 'buscar_dados' 'home.Produto' %}" value="{{item_pedido.produto.nome}}" data-hidden="#id_produto" >
    </p>
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-sm">Salvar Produto</button>
    <button type="button" onclick="location='{% url 'form_pagamento' pedido.id %}'" class="btn btn-primary btn-sm">Registrar Pagamento</button>
</form>

<!-- Itens já adicionados ao pedido -->
<h5>Itens do Pedido</h5>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Preço Unitário (R$)</th>
            <th>Total (R$)</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for item in pedido.itempedido_set.all %}
        <tr>
            <td>{{ item.produto.nome }}</td>
            <td>{{ item.qtde }}</td>
            <td>{{ item.preco_formatado }}</td>
            <td>{{ item.total }}</td>
            <td>
              <a href="{% url 'editar_item_pedido' item.id %}" class="btn btn-warning btn-sm">Editar</a>
              <a href="{% url 'remover_item_pedido' item.id %}" class="btn btn-danger btn-sm" 
              onclick="return confirm('Tem certeza que deseja remover este item?');">Remover</a>
            </td>         
        </tr>
        {% endfor %}
    </tbody>
</table>
<p>Total do Pedido: R$ {{ pedido.total }}</p>
<p>Total Pago: R$ {{ pedido.total_pago }}</p>
<p>Débito: R$ {{ pedido.debito }}</p>
<hr>


<a href="{% url 'remover_pedido' pedido.id %}" class="btn btn-danger btn-sm" 
onclick="return confirm('Tem certeza que deseja remover este registro?');">Excluir</a>


{% endblock conteudo %}

{% block javascript %}
<script>
    $('#confirm-btn').confirmation({
      rootSelector: '#confirm-btn',
      title: 'Você tem certeza?',
      btnOkLabel: 'Sim',
      btnCancelLabel: 'Não',
      onConfirm: function() {
        alert('Confirmado!');
      },
      onCancel: function() {
        alert('Cancelado!');
      }
    });
  </script>

{% endblock javascript %}

templates/pedido/form.html
{% extends "base.html" %}

{% block titulo_conteudo %} Novo Pedido {% endblock titulo_conteudo %}

{% block conteudo %} 

<p>
    <label for="id_cliene">Cliente:</label>
    <span class="form-control" >{{form.instance.cliente.nome}}</span>
     <input type="hidden" value="{{form.instance.cliente.id}}" name="cliente" id="id_cliente">
  </p>
  <p>
    <label for="id_data">Data:</label>
    <span class="form-control" >{{ data_atual|date:"d/m/Y H:i" }}</span>
   </p>

  <p>
    <label for="id_status">Status:</label>
    <span class="form-control" >{{form.instance.get_status_display}}</span>
   </p>

<form method="post">
    {% csrf_token %}    
    {{ form.as_p }}
    <button class="btn btn-primary btn-sm" type="submit">Salvar</button>
</form>


{% endblock conteudo %}

{% block javascript %}

{% endblock javascript %}

templates/pedido/lista.html
{% extends "base.html" %}

{% block titulo_conteudo %} Listagem de Pedidos {% endblock titulo_conteudo %}

{% block conteudo %} 

<div class="barrabotoes">
  <button onClick="location='{% url "form_cliente" %}'" type="button" class="btn btn-primary btn-sm">Inserir Novo</button>
  <button onClick="location='{% url "pedido" %}'" type="button" class="btn btn-primary btn-sm">Recarregar</button>

</div>

<table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Cliente</th>
        <th>Data</th>
        <th>Situação</th>
        <th>Produtos</th>
        <th>Total (R$)</th>
        
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
    {% for pedido in lista_pedidos %}
      <tr>
        <td>{{ pedido.id }}</td>
        <td>{{ pedido.cliente.nome }}</td>
        <td>{{ pedido.data_pedidof}}</td>
        <td>{{ pedido.get_status_display }}</td>
        <td>{{ pedido.qtdeItens}}</td>  
        <td>{{ pedido.total}}</td>      
        <td>
          <button onClick="location='{% url 'detalhar_pedido' pedido.id %}'" type="button" class="btn btn-primary btn-sm">Detalhes</button>
          <a href="{% url 'remover_pedido' pedido.id %}" class="btn btn-danger btn-sm" 
          onclick="return confirm('Tem certeza que deseja remover este registro?');">Remover</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


{% endblock conteudo %}

templates/pedido/pagamento.html
{% extends "base.html" %}

{% block titulo_conteudo %} Registro de Pagamento {% endblock titulo_conteudo %}

{% block conteudo %} 


<p>
    <label for="id_cliene">Pedido:</label>
    <span class="form-control" >{{form.instance.pedido}}</span>
    
  </p>
  <p>
    <label for="id_data">Data:</label>
    <span class="form-control" >{{ data_atual|date:"d/m/Y H:i" }}</span>
   </p>


<form method="post">
    {% csrf_token %}    
    {{ form.as_p }}
    <button class="btn btn-primary btn-sm" type="submit">Salvar</button>
    <button type="button" onclick="location='{% url 'detalhar_pedido' form.instance.pedido.id %}'" class="btn btn-secondary btn-sm">Voltar</button>

</form>



<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Valor (R$)</th>
      <th>Forma</th>
      <th>Data</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
  {% for pagamento in form.instance.pedido.pagamentos %}
    <tr>
      <td>{{ pagamento.id }}</td>
      <td>{{ pagamento.valor }}</td>
      <td>{{ pagamento.get_forma_display }}</td>
      <td>{{ pagamento.data_pgtof }}</td>

      <td>
        <a href="{% url 'editar_pagamento' pagamento.id %}" class="btn btn-warning btn-sm">Editar</a>
        <a href="{% url 'remover_pagamento' pagamento.id %}" class="btn btn-danger btn-sm" 
        onclick="return confirm('Tem certeza que deseja remover este registro?');">Excluir</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<p>Total do Pedido: R$ {{ pedido.total }}</p>
<p>Total Pago: R$ {{ pedido.total_pago }}</p>
<p>Débito: R$ {{ pedido.debito }}</p>
<hr>
{% endblock conteudo %}

{% block javascript %}
{% endblock javascript %}